---
title: "Week 1 Exercises"
format: html
editor: visual
---

## Week 1

**1.1.1 Vectors**

Exercise 1.1

```{r}

#Identifies type of vector
typeof(mtcars)

#Identifies class
class(mtcars)

#Identifies number of rows (observations) in df
nrow(mtcars)

#Identifies number of columns in df
ncol(mtcars)

#Identifies number of columns in df
length(mtcars)

#Identifies number of rows and columns in df
dim(mtcars)

#Identifies row names (value in the first column) in df
rownames(mtcars)

#Identifies column names in df
colnames(mtcars)
```

Exercise 1.2

```{r}

#works
T <- 123

# gave error "Error in TRUE <- 123 : invalid (do_set) left-hand side to assignment"
TRUE <- 123
```

Exercise 1.3

```{r}

lgl <- c(TRUE, FALSE, NA)
int <- c(1L, 6L, NA, 10L)
dbl <- c(1, NA, 2.5, 4.5)
chr <- c(NA, "these are", "some strings")

c(1, FALSE) #numeric 1 0
c("a", 1) #character "a" "1"
c(TRUE, 1L) #numeric 1 1
```

Exercise 1.4

```{r}

as.integer(FALSE) #0
as.integer(TRUE) #1
```

Exercise 1.5

```{r}

x <- sample(c(TRUE, FALSE), size = 75, replace = TRUE)
sum(x)

mean(x)
sum(x) / length(x)
#they do produce the same result
```

**1.1.2 Subsetting**

```{r}

mtcars$mpg

x <- list(chr, lgl, letters)
str(x)

names(x) <- c("chr", "lgl", "alphabet")
str(x)

x$alphabet

mtcars[[mpg]]

mtcars[["mpg"]]
```

Exercise 1.6

```{r}

identical(mtcars["mpg"], mtcars$mpg) #false, selects a column in the df
identical(mtcars[["mpg"]], mtcars$mpg) #true, extracts a column in the df
```

Exercise 1.7

```{r}

letters[17]
letters[seq(2, 26, by = 2)]
letters[8:12]
```

```{r}

dbl
dbl[1] <- 10
dbl
dbl[is.na(dbl)] <- 0
dbl
#logical subsetting
```

Exercise 1.8

```{r}

letters[18] <- NA
letters[18]
```

**1.1.3 The most common error you'll see**

```{r}

mean[1:5]
df$col
```

**1.1.4 Data Frames**

```{r}

mtcars[1:2]
mtcars[1:3, ]
mtcars[5, ]
mtcars[1:5, "cyl"]

mtcars$wt > 4
mtcars[mtcars$wt > 4, ]
```

Exercise 1.9

```{r}

mtcars[mtcars$cyl == 4, ]
mtcars[mtcars$mpg > 23, ]
```

```{r}

mtcars[mtcars$carb %in% c(3, 6, 8), ]
mtcars[mtcars$carb == 3 | mtcars$carb == 6 | mtcars$carb == 8, ]
```

**1.2 Search**

```{r}

search()
names(.GlobalEnv)
.secret_var <- 1:10
.secret_var
asdfasdfasdf
find("mtcars")
mtcars <- "this is not the mtcars dataset"
mtcars
find("mtcars")
str(datasets::mtcars)
dplyr::glimpse(datasets::mtcars)
```

**1.2.1 Errors!**

```{r}
library(tidyverse)
library(palmerpenguins)
#table(year)
table(penguins$year)
```

Exercise 1.10

R looked for an object "year" and did not find it. R then searched year and found a function called "year" in the lubridate package

**1.3 dplyr subsetting**

Exercise 1.11

```{r}

library(tidyverse)
nrow(penguins)
penguins |> 
  slice(seq(2, nrow(penguins), by = 2))
penguins |> 
  slice(seq(3, nrow(penguins), by = 3))
```

Exercise 1.12

```{r}

penguins |>
  filter(species == "Gentoo", island == "Biscoe", body_mass_g >= 5000, body_mass_g <= 5500)
```
